// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKBfKvXv2lsa2Z_7f5q_0SpRDvAxO6B7g',
    appId: '1:358216365787:web:14783b2fd685b90e133efe',
    messagingSenderId: '358216365787',
    projectId: 'charities-323d4',
    authDomain: 'charities-323d4.firebaseapp.com',
    storageBucket: 'charities-323d4.appspot.com',
    measurementId: 'G-Q3SGXL9ZGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiZiMn48_pyGCVwI88tfM0CwIKhEH03Tc',
    appId: '1:358216365787:android:3b60be29fc173b0f133efe',
    messagingSenderId: '358216365787',
    projectId: 'charities-323d4',
    storageBucket: 'charities-323d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfF6heuU49ItsLPXhEqlMYtNzYVOGNPpM',
    appId: '1:358216365787:ios:cb17c2e82320f146133efe',
    messagingSenderId: '358216365787',
    projectId: 'charities-323d4',
    storageBucket: 'charities-323d4.appspot.com',
    iosClientId: '358216365787-4pceb65t755iceanqlh2j35a9aneu7tj.apps.googleusercontent.com',
    iosBundleId: 'com.example.charities',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfF6heuU49ItsLPXhEqlMYtNzYVOGNPpM',
    appId: '1:358216365787:ios:cb17c2e82320f146133efe',
    messagingSenderId: '358216365787',
    projectId: 'charities-323d4',
    storageBucket: 'charities-323d4.appspot.com',
    iosClientId: '358216365787-4pceb65t755iceanqlh2j35a9aneu7tj.apps.googleusercontent.com',
    iosBundleId: 'com.example.charities',
  );
}
